- name: Install apt packages
  ansible.builtin.apt:
    name: "{{ apt_packages }}"
    state: present
    update_cache: true
  become: true

- name: Install pip packages
  ansible.builtin.pip:
    name: "{{ pip_packages }}"
  become: true

# https://docs.ansible.com/ansible/latest/collections/community/general/homebrew_module.html
- name: Install homebrew packages
  community.general.homebrew:
    name: "{{ homebrew_packages }}"
  become: false
