# https://github.com/fish-shell/fish-shell#packages-for-linux
- name: Add fish repository
  ansible.builtin.apt_repository:
    repo: ppa:fish-shell/release-3
  become: true

- name: Install fish
  ansible.builtin.apt:
    name: fish
    update_cache: true
  become: true
