- name: Install CUDA keyring
  become: true
  ansible.builtin.apt:
    deb: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-keyring_1.0-1_all.deb
    update_cache: true

- name: Get dash-case name of cuda_version
  ansible.builtin.shell: bash -c 'sed -e "s/\./-/g" <<< $(echo {{ cuda_version }})'
  register: dash_case_cuda_version
  changed_when: false

- name: Install CUDA libraries except for cuda-drivers
  become: true
  ansible.builtin.apt:
    name:
      - cuda-{{ dash_case_cuda_version.stdout }}
    update_cache: true

- name: Install cuda-drivers
  become: true
  ansible.builtin.apt:
    name:
      - cuda-drivers
    update_cache: true
